import type { Metadata } from "next";
import localFont from "next/font/local";
import "./styles/globals.css";
import { Plus_Jakarta_Sans as FontJakarta, Plus_Jakarta_Sans } from "next/font/google";
import { TailwindIndicator } from "@/components/tailwind-indicator";
import { ThemeProvider } from "next-themes";
import Navigation from "@/components/navigation";
import { dashboardConfig } from "@/config/dashboard";

const jakarta = Plus_Jakarta_Sans({ subsets: ["latin"], display: "swap" }); 
const fontJakartaSans = FontJakarta({ subsets: ["latin"], variable: "--font-jakarta-sans", });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ThemeProvider
        attribute="class"
        defaultTheme="light"
        enableSystem
        disableTransitionOnChange
      >
        <body
          className={`${jakarta.className} ${fontJakartaSans.variable} antialiased min-h-screen mx-auto max-w-7xl`}
        >
          <div className="min-h-screen w-full">
            <header className="sticky justify-center items-center flex flex-col w-full top-0 z-40 bg-background">
              <div className="flex h-16 items-center w-full mx-auto justify-between py-4">
                <Navigation items={dashboardConfig.mainNav} />
              </div>
              <div className="border-b h-2 w-screen mx-0 flex justify-center items-center"></div>
            </header>
            <main>{children}</main>
            <footer className="flex flex-col h-16 items-center w-full mx-auto justify-between py-4">
              <div className="border-b h-2 w-screen mx-0 flex justify-center items-center"></div>
            </footer>
          </div>
          <TailwindIndicator />
        </body>
      </ThemeProvider>
    </html>
  );
}
