export const metadata = {
    title: "Create Next App" as string, // Type assertion to ensure it is treated as a string
    description: "Generated by create next app" as string | undefined, // or handle null/undefined properly
  };